[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rustysolana = "DvNkYwKFYEpLvvTgZ9yCEoBwG37d54LxCbJ6X1fBzMyp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/bill/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
