[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rustysolana = "EzN6P2ZuFz8arhAHs59u5vSz2A5X2LFH6Cmb6iVzxX9g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
